### ISSUE TITLE
Change generation to use repo count

### ISSUE THREAD

**Issue by vinomaster** [trustoverip/next-deliverable-num#1]
## Problem

Our deliverables can live as folders in the `deliverables` repo as well as unique repos in the org. The use of PRs as means to establish a unique deliverable ID is no longer adequate.

## Current Approach
The [existing number generator](https://trustoverip.github.io/next-deliverable-num/), which is produced by this repo, calculates the next unique number using:

- https://api.github.com/repos/trustoverip/deliverables/pulls?state=all&per_page=1
- Filter on ```/pulls/```

## Required Change
We need to update the [number generator](https://trustoverip.github.io/next-deliverable-num/) so that it automatically calculates the next available number using the following formula:

```
<Total_ToIP_Organization_Repo_Count> + <Total_Recommendation_Count> + 1
```

## Proposed Solution

1. Determine Repo Count 
    - https://api.github.com/orgs/trustoverip/repos
    - Filter on ```"full_name":```
2. Determine Recommendations Count
     - https://api.github.com/repos/trustoverip/deliverables/contents/recommendations
     - Filter on ```"name":```
3. Add the values from search results from 1 and 2 above, then add 1 to get new unique number.

**Comment by VictorSyntez** [comment]
Currently, next unique number will be 19. Do you want to be able to do it automatically?

**Comment by vinomaster** [comment]
Yes we need a change to the JS code in the [index.html](https://github.com/trustoverip/next-deliverable-num/blob/master/index.html) file. Is this something you can do?

**Comment by vinomaster** [comment]
JS Promise Recommendations by [@dgisolfi](https://github.com/dgisolfi)
